title = "Mambuco"
base_url = "https://mambuco.dev"
description = "I'm Mambuco, a teenage developer and gamer. I talk about myself here, and about topics that often get ignored by the mainstream."

theme = "ametrine"

minify_html = true
compile_sass = true
generate_feeds = true
build_search_index = true

feed_filenames = ["rss.xml", "atom.xml"]

author = "Mambuco"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
smart_punctuation = true
bottom_footnotes = true

[search]
index_format = "elasticlunr_json"

[extra]
accent_color = ["hsl(29, 65%, 31%)", "hsl(29, 72%, 74%)"]

styles = ["mods.css", "deprecated.css"]
scripts = ["js/quicklink.umd.js", "js/prefetch.js"]

issues_url = "https://github.com/mambucodev/my-website/issues"
source_url = "https://github.com/mambucodev/my-website"

copy_button = true
show_reading_time = true
show_comments_qr = true

date_format = "%d %B %Y"
date_format_long = "%d %B %Y, %R (%Z)"
date_locale = "en_IE"

timezone = "Europe/Rome"

[extra.meta]
favicon = "favicon.gif"
apple_touch_icon = "assets/avatar.png"
card = true

[extra.nav]
icon = "https://api.lanyard.rest/604790617138266149.webp"

links = [
    { url = "@/about/index.md", name = "About", icon = "info" },
    { url = "@/socials/index.md", name = "Socials", icon = "at" },
    { name = "My Works", category = [
        { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
        { url = "@/crestfall/_index.md", name = "Crestfall", icon = "joystick", new = true },
        { url = "@/distropedia/_index.md", name = "Distropedia", icon = "books" },
        { url = "@/commissions/index.md", name = "Commissions", icon = "basket" },
    ] },
    { name = "External", category = [
        { url = "https://daudix.one/snug-nook", name = "Snug Nook", icon = "chats" },
        { url = "https://envs.net", name = "Envs.net", icon = "hard-drives" }
    ] }
]

[extra.footer]
copyright = "Â© Mambuco, 2024-$YEAR"
show_fediring = true
show_timestamp = true
show_powered_by = true

socials = [
    { url = "https://wetdry.world/@mambuco", icon = "mastodon" },
    # { url = "https://bsky.app/profile/mambuco.dev", icon = "bluesky" },
    { url = "https://github.com/mambucodev", icon = "github" },
    { url = "https://discord.sadyn.it", icon = "discord" },
]

[extra.fediverse]
host = "wetdry.world"
user = "mambuco"
show_qr = true

[extra.analytics]
service = "umami"
id = "d25bb216-4c7d-43d6-9d16-9b9435a6ae61"
self_hosted_url = "https://umami.mambuco.dev"
